[package]
name = "myco"
version = "0.0.1"
authors = ["Ian Quick <ian.quick@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/ibawt/myco"

[dependencies]
log = "0.3"
env_logger = "0.3"
linenoise-rust = "0.2"

[profile.release]
debug=true
