[package]
name = "rust-lisp"
version = "0.0.1"
authors = ["Ian Quick <ian.quick@gmail.com>"]
[dependencies]
regex = "0.1.8"

[dependencies.readline]
git = "https://github.com/ibawt/rust-readline.git"
rev = "266a87153a550720724b909e3029f0598ad664fd"
